# Generated by Django 3.1.5 on 2021-01-25 09:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(default='text'),
            preserve_default=False,
        ),
    ]
